import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

export const AttendancePDF = ({ dateFilter, filteredData }) => {
  const styles = StyleSheet.create({
    page: {
      padding: 40,
      backgroundColor: "#f8f9fa",
      fontFamily: "Helvetica",
    },
    title: {
      fontSize: 24,
      fontWeight: "bold",
      textAlign: "center",
      marginBottom: 30,
      color: "#333",
    },
    subtitle: {
      fontSize: 16,
      textAlign: "center",
      marginBottom: 30,
      color: "#555",
    },
    table: {
      display: "table",
      width: "100%",
      borderStyle: "solid",
      borderWidth: 1,
      borderColor: "#ddd",
      borderRadius: 8,
      overflow: "hidden",
    },
    tableRow: {
      flexDirection: "row",
      alignItems: "center",
    },
    tableHeader: {
      backgroundColor: "#007bff",
      color: "#fff",
      padding: 12,
      textAlign: "center",
      fontWeight: "bold",
      fontSize: 12,
    },
    tableCell: {
      padding: 12,
      textAlign: "center",
      borderBottom: "1px solid #ddd",
      fontSize: 12,
      color: "#333",
    },
    evenRow: {
      backgroundColor: "#f1f1f1",
    },
    oddRow: {
      backgroundColor: "#ffffff",
    },
    section: {
      marginBottom: 30,
    },
    footer: {
      textAlign: "center",
      fontSize: 10,
      color: "#888",
      marginTop: 40,
    },
    pageNumbers: {
      position: "absolute",
      bottom: 30,
      right: 40,
      fontSize: 10,
      color: "#888",
    },
  });

  return (
    <Document>
      <Page style={styles.page}>
        <Text style={styles.title}>
          Attendance Report - {dateFilter ? `Date: ${dateFilter}` : "All Dates"}
        </Text>
        <Text style={styles.subtitle}>Generated on {new Date().toLocaleDateString()}</Text>

        <View style={styles.section}>
          <View style={styles.table}>
            {/* Table Header */}
            <View style={styles.tableRow}>
              <Text style={[styles.tableCell, styles.tableHeader]}>Name</Text>
              <Text style={[styles.tableCell, styles.tableHeader]}>Date</Text>
              <Text style={[styles.tableCell, styles.tableHeader]}>Status</Text>
            </View>

            {/* Table Rows */}
            {filteredData.map((attendance, index) => (
              <View
                style={[
                  styles.tableRow,
                  index % 2 === 0 ? styles.evenRow : styles.oddRow,
                ]}
                key={attendance.id}
              >
                <Text style={styles.tableCell}>{attendance.name}</Text>
                <Text style={styles.tableCell}>{attendance.date}</Text>
                <Text style={styles.tableCell}>{attendance.status}</Text>
              </View>
            ))}
          </View>
        </View>

        <Text style={styles.footer}>Generated by Attendance Management System</Text>
        <Text style={styles.pageNumbers}>Page 1 of 1</Text>
      </Page>
    </Document>
  );
};
